### DISCUSSION TITLE
Trouble setting up first user (Docker Compose)

### DISCUSSION THREAD

**Discussion by flborn** [afaneca/myfin#462] [Q&A] [answered]
Hi,

I really like the application and would like to host it locally. 
I am using the provided docker compose file and am aware that I have to fill the SMTP server env variables.

However I tried with several email providers (gmail, gmx) and when I want to sign up an account I get the error message
"Something went wrong. Please, try again."

I tried again - didn't help :)

Also, there is no further error message whatsoever, so it's a bit tough for me to tell what exactly went wrong.

The configuration is as follows
`- SMTP_HOST=mail.gmx.net`
`- SMTP_PORT=465`
`- SMTP_SECURE=true`
`- SMTP_USER=**********@gmx.at`
`- SMTP_PASSWORD=*****************`

Am I missing something, or is there an option to create an user account without email verification?

**Comment by afaneca** [comment]
Hi @flborn,
You don't need SMTP configured to start using MyFin locally. SMTP is only used for the "forgot my password" flow, so you can ignore that for now, if you wish.

When you open MyFin on the browser, are you redirected to the setup flow or login page?

**Reply by flborn** [reply]
I'm redirected to the login page

**Reply by afaneca** [reply, marked as answer]
That seems to indicate that your frontend can't establish a connection to the backend (myfin-api). Make sure your api is up and running on a publicly accessible url and that you're setting `VITE_MYFIN_BASE_API_URL` environment variable to that same URL, as per [this wiki page](https://github.com/afaneca/myfin/wiki/Project-Setup).

**Reply by flborn** [reply]
Now I get it, it's probably also what the other guy was writing.

The API container needs to be publicly available, not just within the docker network.
In my case it means, the port has to be exposed on the host machine (3001, or something else if it's not free - 9001 in my case) and there has to be a local dns entry for that container, in my case myfin-api.home pointing to the host.

Then `VITE_MYFIN_BASE_API_URL=http://myfin-api.home:9001` will work.

**Reply by pixelthorn** [reply]
Sorry for replying to an old thread, but I am in the same boat, unable to create a user, but am unsure how to create a local dns entry for the api container (I have a reverse proxy set up but that is apparently not enough). 

This should be in  the setup guide!

**Reply by afaneca** [reply]
Hi @pixelthorn,
As discussed earlier in this thread, it's not enough to have the API container only accessible within Docker or via a reverse proxy inside your network. The key point is: the API needs to be **publicly accessible**, or at least reachable by any client that needs to use it, including mobile apps or browsers running on other devices.

That’s why simply setting up a local DNS or reverse proxy might not work if those clients can't reach the API. In most setups, that means exposing the API port on the host machine and making sure there's a valid hostname that resolves to the host from any client device.



> This should be in the setup guide!

Thanks for pointing that out. I’ll make sure to improve that section in the setup guide as soon as possible.

**Reply by networked47** [reply]
Hi,

I've also struggled with this too. I got all to work without a proxy, but then some functions I want don't work. First I tried with traefik, didn't get it to work and went over to nginx. I've gotten so far as to get the front page to work when proxied, but as things don't go on I'm assuming that the api server doesn't respond or is not reachable. 
I ended up trying all kinds of ways to use a DNS address, but in the end I ended up using the IP straight, also checking that I can access the IP and/or dns name from the browser I'm running from and I still can't get it to work.

**Reply by afaneca** [reply]
Hi @networked47, 
Could you provide a few more details about what exactly is failing? Are you able to see any logs/error messages?

**Reply by networked47** [reply]
Hi,

what I assume is failing is the frontend communicating with the api. First i assume it was down to name resolution, so I sh:ed into the frontend container and pinged myfin-api: no response, proxy-redirect FQDN: no response, servername: no response, server IP: response.
from my client I checked that the api server as running by using the server IP or name and port 3001. Got responses.

When I'm running on http, it all works, but when I switch to the myfin.server.local adress that then redirects to a https, I get the frontend login and the login that I just created on http no longer works. I also enabled the signup flow and even though I can go through it, when it should have, I get an error message, "something went wrong" or similar, don't recall exactly. 
I looked at the logs on the api container and it just says that it is listening on port 3001.

I also put in the server IP and port into the docker compose, just to be on the safe side, and on a launch I added the api container to every docker network, apart from host. Still no connection or log entry. One change major change I did was to change the API URL from https to http since it wouldn't respond on https and port 3001.

in the frontend I also didn't see anything in the log apart from GET messages for resources on the front page.

The frontend container is the only one that is connected to two networks, the myfin, where the others also are, and the proxy-net work.

Does this help?

**Reply by afaneca** [reply]
Hi again, 
here's a few things that might be related to the issues you're facing:
- if you serve the frontend over https and then try to access the api from http (or vice-versa), most browsers will block the requests, for  being [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content). You'll have to use the same schema (preferably https) for both to allow them to communicate.
- From the same browser you're using to access the frontend, if you try to access the API endpoint from another tab, what response does it give you? If your API instance is correctly configured and accessible from that browser, you should see [this output](https://api.myfin.afaneca.com) or similar:
````json
{"info":"MyFin API","version":"3.3.0"}
````
- When those errors occur on the frontend, could you check the developer tools (console and network tabs) for errors? That should give us deeper insight into what's actually going on here.

**Reply by networked47** [reply]
Hi,

should have thought about that first one, my mistake. I went back to putting https for the API, but now I get a SSL protocol error.

One thing that I did have problems with before is name resolution, in that the myfin.server.local name doesn't work inside the containers, despite the server, that operates the DNS, is set to respond and the resolv.conf in the container has it, so I'm addressing the api with the IP and port 3001.

When I adress the IP and 3001 over http, then I get the correct response back from the api:
`{"info":"MyFin API","version":"3.3.0"}`

**Comment by Uuugh** [comment]
So I'm sorry. But I am missing the answer to the initial login credentials.
I am currently accessing the frontend locally @ http://192.168.0.103:8181 where I am greeted with a login page. 
Any attempt to register (I have gmail info for smtp) is answered with "Something went wrong. Please, try again."
If I attempt to login with made up login I get "Invalid credentials. Try again!"  (As I'd expect.)

VITE_MYFIN_BASE_API_URL=https://192.168.0.103:3001
LOGGING="true" # THINK TWICE ABOUT ENABLING IN PROD
BYPASS_SESSION_CHECK="true" # DO NOT ENABLE IN PROD
ENABLE_USER_SIGNUP=true

The browser output for http://192.168.0.103:3001 is {"info":"MyFin API","version":"4.5.0"}
I opened the users table and the table has no users. What am I missing?

**Reply by afaneca** [reply]
Hi @Uuugh,

There are no default/initial login credentials.

On a fresh install, the first time you access the frontend you should be redirected into the onboarding flow, where you create the first user account and choose the initial settings. Since you are seeing the login page instead, it sounds like the frontend may not be communicating correctly with the backend during that initial setup check.

Looking at the info you provided, I noticed your frontend is configured with:

```VITE_MYFIN_BASE_API_URL=https://192.168.0.103:3001```

but you verified the API in the browser using:

`http://192.168.0.103:3001`

Unless you have SSL/TLS configured in front of the API, those should match. Since you are testing locally over HTTP, try changing it to:

`VITE_MYFIN_BASE_API_URL=http://192.168.0.103:3001`

Then recreate/restart the frontend container so the updated value is applied.

Also, I’d recommend setting this back to false:

`BYPASS_SESSION_CHECK=false`

That setting is not needed for the initial setup flow.

**Reply by Uuugh** [reply]
Hi @afaneca. I appreciate the reply.
I set BYPASS_SESSION_CHECK=false , pruned the stack, erased the db, and set VITE_MYFIN_BASE_API_URL=http://192.168.0.103:3001

I also found that I need to adjust the docker compose file. May I suggest the following docker-compose.yaml?
```
services:
  myfin_frontend:
    image: ghcr.io/afaneca/myfin:latest
    container_name: myfin_frontend
    depends_on:
      myfin_api:
        condition: service_healthy
    ports:
      - "8181:80"
    environment:
      - VITE_MYFIN_BASE_API_URL=${VITE_MYFIN_BASE_API_URL}
    restart: ${RESTART}
 
  myfin_api:
    image: ghcr.io/afaneca/myfin-api:latest
    container_name: myfin_api
    depends_on:
      myfin_db:
        condition: service_healthy
    ports:
      - "${PORT:-3001}:3001"
    environment:
      # Database Configuration
      - DB_NAME=${DB_NAME:-myfin}
      - DB_USER=${DB_USER:-myfin_user}
      - DB_PW=${DB_PW:-myfin_password}
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-myfin_db}
      - DATABASE_URL="mysql://${DB_USER}:${DB_PW}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      # Application Configuration
      - PORT=${PORT:-3001}
      - LOGGING=${LOGGING:-false}
      - BYPASS_SESSION_CHECK=${BYPASS_SESSION_CHECK:-false}
      - ENABLE_USER_SIGNUP=${ENABLE_USER_SIGNUP:-true}
      # Reverse proxy trust for Express
      # - TRUST_PROXY=1 trusts the first proxy hop (Traefik / Nginx proxy in front)
      # - Override with other values as needed (see README/.env.example)
      - TRUST_PROXY=1
    restart: ${RESTART}

  myfin_db:
    image: mysql:8.4
    container_name: myfin_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW:-myfin_password}
      MYSQL_DATABASE: ${DB_NAME:-myfin}
      MYSQL_USER: ${DB_USER:-myfin_user}
      MYSQL_PASSWORD: ${DB_PW:-myfin_password}
    volumes:
      - ${MNT_DOCKER}/myfin/mysql:/var/lib/mysql
    restart: ${RESTART}

networks: {}
```

.... although you may want to replace my volume at the end {MNT_DOCKER}/myfin/mysql:/var/lib/mysql with the original 
```
volumes:
  db_data:
```

Thanks again!
