### DISCUSSION TITLE
Can't use MyFin on kubernetes without building a custom image

### DISCUSSION THREAD

**Discussion by KitAmbraid** [afaneca/myfin#471] [Q&A]
The docker image doesn't actually read `VITE_MYFIN_BASE_API_URL` from the env at boot, it [hardcodes its value](https://github.com/afaneca/myfin/blob/7.5.4/Dockerfile#L45) at build

Which means a deployment like this (heavily trimming to leave only the relevant parts):

```yaml
Pod Template:
  Containers:
   myfin-frontend:
    Image:      ghcr.io/afaneca/myfin:7.5.4
    Port:       80/TCP
    Environment:
      VITE_MYFIN_BASE_API_URL:  https://api.myfin.mydomain.com/
```

Will always try to connect to `http://myfin-api:3001`

![Image](https://github.com/user-attachments/assets/8d6b2dbb-aae4-4c50-be86-a74db232f733)

**Comment by afaneca** [comment]
Hi @KitAmbraid,
This is related to the way React/Vite deal with environment variables. They access the variables at build time and then hardcode that value in the final static files that result from the build.

This is why in our Dockerfile we're using a placeholder approach - we set `VITE_MYFIN_BASE_API_URL="myfin-api-url-placeholder"` during build, then at runtime we use a script to search for all references to this placeholder in the static files and replace it with the actual environment variable value:

````sh
find /usr/share/nginx/html -type f -name "*.js" -exec sed -i "s|myfin-api-url-placeholder|$VITE_MYFIN_BASE_API_URL|g" {} +
````
I don't have Kubernetes experience, but this approach works fine with our [docker-compose](https://github.com/afaneca/myfin/blob/7.5.4/docker-compose.yml) setup:

````yml
myfin-frontend:
    image: ghcr.io/afaneca/myfin:latest
    container_name: myfin-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      myfin-api:
        condition: service_healthy
    environment:
      - VITE_MYFIN_BASE_API_URL=http://whatever-you-want.here
````

Any ideas as to why it wouldn't be working for your kubernetes config?
