### ISSUE TITLE
Tweak nord nightfall theme

### ISSUE THREAD

**Issue by afaneca** [afaneca/myfin#351]
# Common
````css
.dataTables_wrapper .dataTables_filter input {
    margin-left: 0;
}
````

# Nord nightfall
````css
--main-blue-background: #192431;

table.dataTable thead th, table.dataTable thead td {
    border-bottom: 1px solid var(--main-body-background);
    background: var(--main-blue-background);
}

table.dataTable.hover tbody tr:hover, table.dataTable.display tbody tr:hover {
    background-color: var(--main-blue-background) !important;
}

table.dataTable.stripe tbody tr.odd, table.dataTable.display tbody tr.odd {
    background-color: var(--main-body-background);
}

table.dataTable tbody tr {
    background-color: var(--main-body-background);
}

````
