### ISSUE TITLE
Can't use MyFin on kubernetes without building a custom image

### ISSUE THREAD

**Issue by KitAmbraid** [afaneca/myfin#468]
The docker image doesn't actually read `VITE_MYFIN_BASE_API_URL` from the env at boot, it [hardcodes its value](https://github.com/afaneca/myfin/blob/7.5.4/Dockerfile#L45)

Which means a deployment like this (heavily trimming to leave only the relevant parts):

```yaml
Pod Template:
  Containers:
   myfin-frontend:
    Image:      ghcr.io/afaneca/myfin:7.5.4
    Port:       80/TCP
    Environment:
      VITE_MYFIN_BASE_API_URL:  https://api.myfin.mydomain.com/
```

Will always try to connect to `http://myfin-api:3001`

![Image](https://github.com/user-attachments/assets/8d6b2dbb-aae4-4c50-be86-a74db232f733)
